[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
time_locked_wallet = "8H3kyZCtLpV3ugf8hVAYHL5sPuYz92jbGaqLAjz7uzEp"
[programs.devnet]
time_locked_wallet = "899SKikn1WiRBSurKhMZyNCNvYmWXVE6hZFYbFim293g"
[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
